### ISSUE TITLE
It seems to have some memory leak in vs2013 

### ISSUE THREAD

**Issue by aricatamoy** [log4cplus/log4cplus#119]
I use log4cplus-master in my project, and use

	_CrtSetDbgFlag(_CrtSetDbgFlag(_CRTDBG_REPORT_FLAG) | _CRTDBG_LEAK_CHECK_DF);

to check whether it exists memory leak.

**Comment by wilx** [comment]
I have recently fixed a leak in `loggingserver`. Is that it?

If it is different leak, what is your configuration? How do you use log4cplus? How do I reproduce the leak? How big is the leak? Please provide some details.

**Comment by aricatamoy** [comment]
The code is here:
#include "log4cplus/initializer.h"

int main(int argc, char *argv[])
{
	_CrtSetDbgFlag(_CrtSetDbgFlag(_CRTDBG_REPORT_FLAG) | _CRTDBG_LEAK_CHECK_DF);
	log4cplus::Initializer();
	return 0;
}

I use log4cplus-master, edit the *.vcxproj file, replace "v140" to "v120" to compile it in my vs2013. It reports memory leaks.  It's possibly cause by stringhel

Here is the output:
Detected memory leaks!
Dumping objects ->
{1428} normal block at 0x004D7778, 32 bytes long.
 Data: <..\src\stringhel> 2E 2E 5C 73 72 63 5C 73 74 72 69 6E 67 68 65 6C 
{1427} normal block at 0x004D7730, 8 bytes long.
...

**Comment by wilx** [comment]
Leaks like this have been reported few times already. Unless this leak actually accumulates during longer run time, I do not think it is an issue. I think the problem is that the leaks reporting routine runs before the memory is actually deallocated. There is some thread-local storage that gets freed only at the very end of threads execution or process execution.

**Comment by aricatamoy** [comment]
ok, thank you very much.
