### ISSUE TITLE
variable 'tistringstream blah_blah_blah' has initializer but incomplete type

### ISSUE THREAD

**Issue by xiaoshuang-lu** [log4cplus/log4cplus#127]
We will encounter this kind of compiling errors without `sstream` included.

e.g.

````{.cpp}
# include <log4cplus/streams.h>

::log4cplus::tistringstream istringstream;
````

**Comment by wilx** [comment]
This is intentional. This is to avoid dragging in headers everywhere that are not needed everywhere.

**Comment by xiaoshuang-lu** [comment]
Hi Václav Haisman,

Is it reasonable for users to include `sstream' manually when they instantiate istringstream defined in `log4cplus/streams.h'?  I am afraid not.

Your sincerely,
Xiaoshuang

**Comment by wilx** [comment]
@xiaoshuang-lu It is reasonable not to have `sstream` dragged in just because you want to use, say, `tcout`. These headers are not really general purpose headers. They are log4cplus implementation headers. Once you hit and solve this once, it is not that hard to remember to include `sstream` when you want to use one of the string streams typedefs.
