### ISSUE TITLE
Question: Plan on 2.0 release?

### ISSUE THREAD

**Issue by biskit-eater** [log4cplus/log4cplus#187]
The 1.2x release is not C++11 compatible (build fails when using GCC 5.4 and probably 6.x). It would be nice to have a stable, C++11 compatible version. Is there a 2.0 release (tag) planned soon?

**Comment by wilx** [comment]
Last time I checked it did build as C++11. Do you have concrete errors to show?

To answer your question, the master branch is C++11 only and only misses, IIRC, `TimeBasedRollingFileAppender` which is currently only on 1.2.x branch. I personally do not have the willpower to try to port to master.

@cfyzium: Could you port `TimeBasedRollingFileAppender` to master branch?

**Comment by biskit-eater** [comment]
Thanks for the quick reply. Yes it does build, but I get linker errors when I try to use the library in a project that is built for C++11- unresolved symbol on the move constructors. I can build a sample if you want.

I'm on Ubuntu, and I was just doing apt-get liblog4cplus-dev. With the latest version of Ubuntu (16.04) which uses GCC 5.4, any projects compiled with -std=c++11 or -std=c++14 have link errors with log4cplus. I get the same errors whether I use the version in Ubuntu's repository or whether I get 1.2.x and build locally. So however the package maintainers are building log4cplus, it isn't compatible with c++11. If I get master and build it works fine.

**Comment by wilx** [comment]
You have to compile both log4cplus and your application using the same standard. If you compile log4cplus with `CXXFLAGS=-std=c++11` then it will link, most likely.

**Comment by biskit-eater** [comment]
I agree with you. I will try that. However it would still be handy to have a 2.x release make it into standard linux distros, so future developers can just do 'apt-get liblog4cplus-dev' and have it work.

Thanks again for your time and quick responses.

**Comment by cfyzium** [comment]
@wilx Yes, I will port it. Though I'll only be able to get to it in about a week or even two =/.

**Comment by wilx** [comment]
https://github.com/log4cplus/log4cplus/issues/187#issuecomment-235625135:
> Yes, I will port it. Though I'll only be able to get to it in about a week or even two =/.

That is completely fine. :)

**Comment by dvj** [comment]
Is the `TimeBasedRollingFileAppender` the only thing holding back a 2.0 release? Is there a checklist for readying 2.0? 

@cfyzium Did you already take a look at this, if so, did you find any problems or have any difficulties?

**Comment by cfyzium** [comment]
I'm sorry for stalling this. I've more or less got back, so I expect to resolve it within a few days. There should not be any difficulties really, the code is rather straightforward.

**Comment by cfyzium** [comment]
Well, pull #209.

Somehow CI pull-request checks fail due some internal CI problems (appveyor trying to build with unsupported VC12, travis-ci probably has configuration issues and fails C compiler check).

I've just noticed there is an issue #207, I'll have to look into it. The version from pull #209 is a simple port, most likely it has the same problem.

On the point of 2.0 release, how strictly C++11 is it planned to be? There are a few places that looks nonstandard, like using custom intrusive shared pointer instead of std::shared_ptr (e. g. SharedRollingFileAppenderPtr), custom synchronization primitives (e. g. Mutex which is a thin wrapper around the standard mutex), custom threading and thread-local constructs. Are these just artifacts from ongoing C++03 -> C++11 transition?

**Comment by wilx** [comment]
> I've just noticed there is an issue #207, I'll have to look into it. 

Please do.

> On the point of 2.0 release, how strictly C++11 is it planned to be? There are a few places that looks nonstandard, like using custom intrusive shared pointer instead of std::shared_ptr (e. g. SharedRollingFileAppenderPtr), custom synchronization primitives (e. g. Mutex which is a thin wrapper around the standard mutex), custom threading and thread-local constructs. 

  - Well, I think we could gradually remove the thin mutex and other wrappers. 
  - However, the intrusive reference counting should stay, for now at least.
  - Some sort of custom threading will always be necessary since we are dealing with POSIX signals as well. However, it could be changed to use `packaged_task` or such instead of inheritance.
  - Thread-local storage is a must have, so unless we have a standard C++11 replacement, it will have to stay.

> Are these just artifacts from ongoing C++03 -> C++11 transition?

Pretty much. My aim was to use the most interesting features without necessarily redesigning everything from scratch. But more C++11-esque style can be used if it is beneficial.

**Comment by wilx** [comment]
To be clear, I do not think that removing all the wrappers, etc., is a requirement for 2.0. It can wait for later releases, 2.1, etc.

**Comment by wilx** [comment]
FYI, I have just released [2.0.0-RC1](https://sourceforge.net/p/log4cplus/news/2017/02/log4cplus-200-rc1-released/).

**Comment by biskit-eater** [comment]
Excellent thank you!
