### ISSUE TITLE
1.1.x branch Visual Studio 2010 compatibilty

### ISSUE THREAD

**Issue by wilx** [log4cplus/log4cplus#188]
See conversation https://github.com/log4cplus/log4cplus/commit/9472c1fd17c1fd552a49ee731b075a95f77e5666#commitcomment-18466897 for detail.

/cc @7kbird

**Comment by 7kbird** [comment]
* The fix 54a381e works. I've test it with VS2010 and VS2013 using cmake
* For your previous question: The SDK shipped with VS2010 is v7.0A, see [Windows SDK history](https://blogs.msdn.microsoft.com/chuckw/2013/10/03/a-brief-history-of-windows-sdks/). I compared `ws2tcpip.h` in both SDK(v7.0A and v7.1A) and they were identical, so I believe `VS2012/2013`  with SDK 7.1A should also fail to compile with previous `REL_1_1_3-RC6`. I've tested VS2013(with cmake), it also fail to compile `REL_1_1_3-RC6` on SDK 8.1
* This issue is not only the CMake problem.The solution file in `msvc10` folder also fail to compile because `_WIN32_WINNT` is set to `0x0501` by default.

**Comment by wilx** [comment]
> This issue is not only the CMake problem. The solution file in msvc10 folder also fail to compile because `_WIN32_WINNT` is set to `0x0501` by default.

I do not understand this statement. According to what I see in the SDK, setting the `NTDDI_VERSION` to `0x05010200` should make the condition true. What I did in the proposed patch is that I have synchronised CMake with Visual Studio 2010 solution. But now you are telling me the Visual Studio 2010 is broken as well?

```cpp
#if (NTDDI_VERSION >= NTDDI_WINXPSP2) || (_WIN32_WINNT >= 0x0502)
WINSOCK_API_LINKAGE
VOID
WSAAPI
FreeAddrInfoW(
    __in_opt        PADDRINFOW      pAddrInfo
    );
```

**Comment by 7kbird** [comment]
Sorry, VS2010 solution on branch `1.1.x-vs2010-freeaddrinfo` is alright, my bad:stuck_out_tongue_closed_eyes:.

I tested the vs2010 solution on `REL_1_1_3-RC6` and mistakenly thought it's still broken because you only change the cmake files on 54a381e. But now I find dfa775f  already fixed the problem, just not merged to `REL_1_1_3-RC6` yet. This issue can be closed.

**Comment by wilx** [comment]
I merged in the patch and it should be fixed in the HEAD of the branch now.
