### ISSUE TITLE
C++ interface/class wrapper for log4cplus macros

### ISSUE THREAD

**Issue by gadh** [log4cplus/log4cplus#236]
i want to create my own logger class that will wrap the log4cplus library (VS2015), but i'm having trouble calling the log4cplus logging macros from my class, it just don't fit. do you have any other high level interface/class/functions i can call from mine without using the macros ?
my logging function, for example: MyLog(logger_instance, log_level, msg1 << msg2 << msg3);

**Comment by wilx** [comment]
The logging macros are a wrapper of already public interface. The idea is that you create an instance of `InternalLoggingEvent` and you give it to `Logger` using either `Logger::log()`, if you want log level threshold checking/filtering on the `Logger` instance, or using `Logger::forcedLog()`, if you want to avoid the log level threshold checking/filtering completely. 

How you create the message of the `InternalLoggingEvent` is up to you. The macros are macros because something similar without preprocessor is hard.
