### ISSUE TITLE
Disable unicode support on Windows

### ISSUE THREAD

**Issue by mnutzinger** [log4cplus/log4cplus#305]
We're using `log4cplus` in a project that runs on MacOS and Windows. For now we don't want to use unicode, i.e. `wchar`s, but only `char`/`std::string`s. On MacOS that works fine, as we simply don't enable unicode. On Windows however `UNICODE` is `#define`d by  the libraries anyway, even if we disable it for the `log4cplus` build.

Our solutions so far was to rename `UNICODE` within `log4cplus` to something like `<prefix>_UNICODE`, in order to be able to disable it "properly" on Windows. But of course that's very tedious when we want to update to a newer version of `log4cplus`.

So my questions are: (1) Is there a reason why the option is called `UNICODE`, which clashes with the `#define` exported by Windows libraries, and (2) if we submitted a PR changing that symbol, would you consider that?

**Comment by wilx** [comment]
Ad (1). The point of using `UNICODE` in log4cplus' headers is to match the mode with the environment it is used in. (2) I would likely reject such pull request.

I strongly suggest you use the Unicode build of log4cplus on Windows. Is there a particular reason why you want to use non-Unicode build of log4cplus on Windows at this time and age?

**Comment by mnutzinger** [comment]
I see. Our reason for using the non-unicode build is that we're supporting both, MacOS and Windows, and only print UTF-8 strings, which works correctly with the non-unicode build of `log4cplus`.

In order to use a `UNICODE`-enabled build we would need to change all our UTF-8 strings to UTF-16.

**Comment by wilx** [comment]
UTF-8 is not that well supported on Windows. If your internal representation is UTF-8 and you want to print those strings then you will indeed have to convert to UTF-16, if you want to use `UNICODE` enabled log4cplus. However, if you are only concerned about UTF-8 in log files, you can use `FileAppender` and [imbue](http://log4cplus.sourceforge.net/docs/html/classlog4cplus_1_1FileAppenderBase.html#a566dc5c29b8ebe79334837b94763c235) it with UTF-8 aware [codecvt facet](https://github.com/log4cplus/log4cplus/blob/master/include/log4cplus/configurator.h#L84).

**Comment by salessandri** [comment]
Hi, there.

I see the way the `UNICODE` flag is being used as problematic. It is currently given as a compile time option [CMakeLists.txt:77](https://github.com/log4cplus/log4cplus/blob/master/CMakeLists.txt#L77):

```
option(UNICODE "Build with tchar = wchar_t" ${UNICODE_DEFAULT})
```

But then there is no way to use that option. `UNICODE` is exported by Windows, leading to linker errors of missing symbols as the client application will see different definitions than the ones provided by the compiled library with the option disabled.

I think that there are two reasonable options here: (a) remove the optionality and force the clients to use the definitions established by the environment or (b) provide a different flag than the one used by the system (like `LOG4CPLUS_UNICODE`) and use that flag to determine the type (default value dependant on the platform).

I don't like the first approach because things are implicit: type definitions depend on system state rather than explicit options at compile time. Also, it can have nasty side effects if the types that the headers define can be affected by later changes in the environment.

The cons of the latter is how do you keep the definitions that were used at compile time of the library. So that if compiled with `LOG4CPLUS_UNICODE` activated, the client doesn't need to set that define when compiling the projects that use log4cplus.
There is an easy solution to this which is to generate a `config.h` file during the cmake configure step that will be exported along with the includes. This was the approach taken in the libtins project: https://github.com/mfontanini/libtins/blob/master/include/tins/config.h.in

This gives the clients of log4cplus the most optionality in terms of usage and the most safety. The environment cannot mess with the definitions established when compiling the library.

**Comment by wilx** [comment]
`UNICODE` is defined by default empty project created by Visual Studio because it is a sane default. However, you can change the setting of your application and turn it off. Log4cplus simply follows the mode set up by the application that uses it.

**Comment by wilx** [comment]
> I must agree with the reporter. Despite having compiled log4cplus with UNICODE=0 I actually cannot use library on Windows as UNICODE is used also as switch in include files not allowing to properly compile anything using this library. Any tries of forcing UNICODE to false fail.

Have you corrected your own project not to define `UNICODE`?

**Comment by pietryna** [comment]
My project does not define UNICODE anywhere.

**Comment by wilx** [comment]
> My project does not define UNICODE anywhere. Unless QGuiApplication using QT is doint this implicitly.

Are you using MSVC with .vcprojx files or are you building using another compiler / build system? It has to be coming from somewhere.

**Comment by pietryna** [comment]
I have cmake project (it does not specity this symbol explicitly) loaded over CLion. Toolchain is MinGW 11.2.0 bundled with QT package.
I've looked deeper and it looks like this symbol is defined by QT MOC autogeneration. I need to understand why part of the team using Ubuntu VM does not have this symbol as in general we're using non-unicode compilation of library, and it works for them OK.
