### ISSUE TITLE
Can I have two DailyRollingFileAppenders logging to the same file?

### ISSUE THREAD

**Issue by lishunan246** [log4cplus/log4cplus#328]
Should the file paths be unique?

**Comment by wilx** [comment]
What do you mean two appenders? Do you mean two instances of the appender in a single process or two processes logging into the same file?

If you have two instances of the same appender in a single process then you should probably reconfigure your logging so that the same appender is used by multiple loggers.

If you want to log using the `DailyRollingFileAppender` from two processes into a single file, then that is also possible but requires locking. Set the `UseLockFile` property to `true`. Log4cplus will then derive the lock file name from the destination log file name and will use it to synchronize writes and rollover between processes.

Also, many people find `DailyRollingFileAppender` behaviour confusing. Maybe you should also take a look at [`TimeBasedRollingFileAppender `](https://github.com/log4cplus/log4cplus/blob/1.2.x/include/log4cplus/fileappender.h#L379). It is similar but works slightly differently and some people find its behaviour more useful.

**Comment by wilx** [comment]
Well, that is unusual. But if you insist on doing that, use the same `UseLockFile` setting on both and I think it should still work.

**Comment by lishunan246** [comment]
Many thanks.
I am going to replace those two appenders with a new one.
