### ISSUE TITLE
Possibility to avoid memory allocation while logging?

### ISSUE THREAD

**Issue by nlohmann** [log4cplus/log4cplus#332]
It seems that at some points during logging, `LOG4CPLUS_C_STR_TO_TSTRING` is called which leads to the creation of a `std::string` object:

https://github.com/log4cplus/log4cplus/blob/5aef420f5e59b72702a2e3121f45e547f6f51ff4/include/log4cplus/tstring.h#L119

This not only seems to have negative impact on performance, but also is problematic as it hinders us to log memory shortages, because once all memory is used, logging does not work any more.

My question is: is it possible to work with preallocated memory?

**Comment by wilx** [comment]
log4cplus tries to keep various buffer around in thread-local storage so once your biggest message gets through, it should pretty much stop allocating. However, there is really not way to make this work only with preallocated buffers, so I have to answer your initial question with: No, it is not possible to avoid memory allocation altogether.

I will explore if the API could be improved with use of `std::basic_string_view` but it would still require memory allocating below the API since logging event object has to be created, etc.

**Comment by nlohmann** [comment]
Thanks for the answer.
