### ISSUE TITLE
MDC in multiple threads

### ISSUE THREAD

**Issue by jgornowich** [log4cplus/log4cplus#425]
I understand from using other logging implementations that the MDC is not generally guaranteed to be automatically inherited from the parent thread.  I am wondering if the correct way of duplicating the same MDC value in multiple threads with log4cplus is to call `log4cplus::getMDC ().put (LOG4CPLUS_TEXT ("key"), LOG4CPLUS_TEXT("someValue"));` or if there is a different available approach?

**Comment by wilx** [comment]
Yes. That looks correct.

**Comment by jgornowich** [comment]
I guess my follow up questions would be is it desirable to have a way to inherit that MDC information from a parent thread and how other's that are using log4cplus may be handling this.

 I have not looked deep enough to determine how hard that would actually be to implement though.

**Comment by wilx** [comment]
Hmm. I think inheriting MDC somehow automatically is not possible. There is no way to know and access MDC of one thread from another. You would have to pass it manually. I think the MDC use-case is like for IP address of a client in a server application or similar. If your request processing transfers between threads, you need to pass all the information including the IP address so that you can set the relevant parts of the MDC.

**Comment by jgornowich** [comment]
Yes that is what I thought was going to be the case.  I actually think in many cases like you suggest it may even been more desirable to have control of the MDC in those separate threads.  

Thank you for the follow up information.
