### ISSUE TITLE
How can log4cplus support UCS-2 encoding log file in linux?

### ISSUE THREAD

**Issue by wlhj131** [log4cplus/log4cplus#470]
Describe your problem here.

For some reasons, my log file need to use UCS-2 encoding in linux os. Possibly CentOS, RedHat, and so on. But I read through docs of log4cplus, I cannot find how to realize it. The logging macros, such as LOG4CPLUS_INFO, would better accept UTF-8, I'm not sure if it is possible. If not, I can also accept it, but the log file should be UCS-2, no matter what the system locale is, no matter what locales the os support.

If log4cplus don't support this requirement, would anyone tell me is it possible to modify the source code and the modification scheme?

Thanks a lot!

Also, provide the following information:

 - version: REL_1_2_2
 - operating system, CPU, bitness: CentOS, RedHat, etc.
 - `configure` script, or CMake, etc., flags and settings: no special configure script

**Comment by wilx** [comment]
It should be possible but it is complicated. You can use [`LOG4CPLUS_REG_LOCALE`](https://github.com/log4cplus/log4cplus/blob/1.2.x/include/log4cplus/spi/factory.h#L268-L270) to register custom locale which has [appropriate codecvt facet](https://en.cppreference.com/w/cpp/locale/codecvt_utf16). Then you can configure the file logger with `.Locale=MyCustomLocale` in configuration file. The codecvt facet in imbued locale should then convert the output to UTF-16.

You can avoid registering the locale with log4cplus if you are constructing the log4cplus appenders in code instead of via configuration file. See [`imbue()`](https://github.com/log4cplus/log4cplus/blob/master/src/fileappender.cxx#L325-L329).

**Comment by wlhj131** [comment]
@wilx 
Thanks for your answer. It works after I follow your instruction, the log file is UTF-16 LE now. But I want the log file begin with BOM (0xFF 0xFE) now, is it possible? Below is my operation that which can output UTF-16 Little Edition without BOM.

1. ./configure ... CPPFLAGS="-DUNICODE"...

2. use  LOG4CPLUS_REG_LOCALE:
`class MyUCS2Locale
    : public LocalFactoryBase<LocaleFactory>
{
public:
    MyUCS2Locale (tchar const * n)
        : LocalFactoryBase<LocaleFactory> (n)
    { }

    virtual
    ProductPtr
    createObject (const log4cplus::helpers::Properties &)
    {
        return std::locale(std::locale(), new std::codecvt_utf16<wchar_t, 0x10ffff, std::little_endian>);
    }
};
`
`spi::LocaleFactoryRegistry& regMy = spi::getLocaleFactoryRegistry();
    //DisableFactoryLocking<spi::LocaleFactoryRegistry> dfl_regMy (regMy);
    reg4._enableLocking(false);
    LOG4CPLUS_REG_LOCALE (regMy, LOG4CPLUS_TEXT("MYLOCALE"), spi::MyUCS2Locale);
    reg4._enableLocking(true);`

3. modify the configuration file:
.Locale = MYLOCALE

**Comment by wilx** [comment]
I have never tried that but what about trying to add the [`generate_header`](https://en.cppreference.com/w/cpp/locale/codecvt_mode) flag to the template.

**Comment by wlhj131** [comment]
That's ok, thanks!
