### ISSUE TITLE
threadCleanup() usage

### ISSUE THREAD

**Issue by wlhj131** [log4cplus/log4cplus#472]
Describe your problem here.

The docs mentioned that, if log4cplus is used as static lib, each thread should call threadCleanup() before terminated. But the usage scenario is always complicated, log4cplus caller always don't know when its thread will exit, such as dll or so developer.

Is there any standard call operation when use static lib? If cannot call threadCleanup(), shared library is necessary?

Also, provide the following information:

 - version: REL_1_2_2

**Comment by wilx** [comment]
This is depends on platform / OS, etc. On Linux, it should work just fine because the thread-local storage functions allow passing a callback. 

On Windows, if you use static libCMT, i.e., not the MSVCRT.dll, there is no way to know when a thread has exited thus it is impossible to do any cleanup. But if you are using MSVCRT.dll, even if log4cplus is a static library, [the cleanup should happen via callbacks embedded into special segment/section](https://github.com/log4cplus/log4cplus/blob/REL_1_2_2/src/global-init.cxx#L542-L570).

**Comment by wlhj131** [comment]
Thanks! It's well that cleanup will be called automatically on linux.
