### ISSUE TITLE
compilation for mips problem

### ISSUE THREAD

**Issue by waikup83** [log4cplus/log4cplus#502]
aws kinesis try to compile log4cplus Rel_1_2_2 but failed in many way

Also, provide the following information:

 - version: REL_1_2_2
 - operating system, CPU, bitness: Cross compiling from linux ubuntu to MIPS
 - `configure` script, or CMake, etc., flags and settings: --host=mips32-linux --enable-threads=no
 - flags and settings used by your application: ...
 - compiler and its version: mips-linux-gnu-g++ (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0

**Comment by wilx** [comment]
I have just installed the MIPS cross build tools with `apt install crossbuild-essential-mips` command. Then I configured log4cplus like this `../configure --build=x86_64-pc-linux-gnu --host=mips-linux-gnu --enable-threads=no`. It all compiled fine. You have to use the proper host argument otherwise it will not find the tools.

**Comment by waikup83** [comment]
cool thanks it's works when a cross compile it alone.
thanks you very much :)
