### ISSUE TITLE
TimeBasedRollingFileAppender and MaxFileSize

### ISSUE THREAD

**Issue by christian-kilsgaard** [log4cplus/log4cplus#516]
I am using TimeBasedRollingFileAppender, and then I also want to add MaxFileSize so that I have a predicable max space for log files.
But I can see in the code it looks like the MaxFileSize property is not being loaded

Is there a way, or do I have to write my own version of TimeBasedRollingFileAppender to get something like this to work?

I am using log4cplus 2.0.4 and TimeBasedRollingFileAppender with the following config

log4cplus.appender.EspCommFile=log4cplus::TimeBasedRollingFileAppender
log4cplus.appender.EspCommFile.FilenamePattern=../log/%d{yyyyMMdd}_comm.log
log4cplus.appender.EspCommFile.UseLockFile=true
log4cplus.appender.EspCommFile.LockFile=../log/comm.lock
log4cplus.appender.EspCommFile.MaxFileSize=40MB
log4cplus.appender.EspCommFile.MaxHistory=7
log4cplus.appender.EspCommFile.CleanHistoryOnStart=false
log4cplus.appender.EspCommFile.RollOnClose=false
log4cplus.appender.EspCommFile.CreateDirs=true
log4cplus.appender.EspCommFile.Append=true
log4cplus.appender.EspCommFile.layout=log4cplus::PatternLayout
log4cplus.appender.EspCommFile.layout.ConversionPattern=[%D{%Y/%m/%d %H:%M:%S.%q}] [%c] %m%n

**Comment by wilx** [comment]
The size based rolling of the log files is incompatible with the `TimeBasedRollingFileAppender` purpose. If we rolled based on size, then there would either be multiple files per period and your use case of predicting the size would not be satisfied or there would be holes in the timeline observable from the logs because the log file would be rolled within a period and some logged events would be lost.

**Comment by christian-kilsgaard** [comment]
Thanks for the quick response

I will do some more thinking on what I really want
